services:
  db:
    image: "postgres:17-alpine3.21"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "<db-password>"
      POSTGRES_USER: "<db-user>"
      POSTGRES_DB: "<db-name>"
