services:
  db:
    image: "postgres:17-alpine3.21"
    ports:
      - "5432:5432"
    env_file:
      - ".env"

  sqlc:
    image: "sqlc/sqlc:1.27.0"
    volumes:
      - "./:/app"
    working_dir: "/app"
    command: "generate"

  migrate:
    image: "migrate/migrate:v4.18.1"
    volumes:
      - "./database/migrations:/migrations"
    working_dir: "/migrations"
    command: "-database $MIGRATE_DATABASE_URL -path /migrations up"
    env_file:
      - ".env"
    depends_on:
      - "db"
