// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Login     string
	Password  string
	Email     sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type UserLog struct {
	ID        int64
	UserID    int64
	Type      string
	Message   sql.NullString
	CreatedAt time.Time
}
